// Language specification constants for sh2
// Used by editor tooling and artifact generation

pub const KEYWORDS: &[&str] = &[
    "func",
    "let",
    "if",
    "elif",
    "else",
    "while",
    "for",
    "in",
    "try",
    "catch",
    "with",
    "env",
    "cwd",
    "log",
    "redirect",
    "subshell",
    "group",
    "spawn",
    "return",
    "exit",
    "break",
    "continue",
    "case",
    "import",
    "set",
];

pub const BUILTINS: &[&str] = &[
    "run",
    "exec",
    "print",
    "print_err",
    "capture",
    "status",
    "pid",
    "ppid",
    "uid",
    "pwd",
    "self_pid",
    "argv0",
    "argc",
    "arg",
    "args",
    "argv",
    "exists",
    "is_dir",
    "is_file",
    "is_symlink",
    "is_exec",
    "is_readable",
    "is_writable",
    "is_non_empty",
    "len",
    "count",
    "join",
    "input",
    "confirm",
    "export",
    "unset",
    "source",
    "sh",
    "wait",
    "cd",
    "heredoc",
    "file",
    "stdout",
    "stderr",
    "stdin",
    "glob",
    "bool_str",
    "sudo",
    "lines",
    "split",
    "trim",
    "replace",
    "matches",
    "contains",
    "contains_line",
    "starts_with",
    "json_kv",
    "load_envfile",
    "save_envfile",
    "parse_args",
    "home",
    "path_join",
    "to_stdout",
    "to_stderr",
    "inherit_stdout",
    "inherit_stderr",
    "read_file",
    "write_file",
    "append_file",
];

pub const OPERATORS: &[&str] = &[
    "==", "!=", "<=", ">=", "<", ">",
    "&&", "||",
    "+", "-", "*", "/", "%",
    "&",
    "=",
    "=>",
    "|",
    ":",
    ".",
    "!",
];

pub const LITERALS: &[&str] = &[
    "true",
    "false",
];
